### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material/TouchTargetKt;

### ISSUE THREAD

**Issue by armutyus** [SmartToolFactory/Compose-Cropper#14]
Edit: I found what is the problem. https://github.com/SmartToolFactory/Compose-Colorful-Sliders/issues/12

I used to use the library without any problems. But right now I am getting an error like this. I tried downgrading and upgrading the Compose version but the result did not change. What could have caused it?

`FATAL EXCEPTION: main
                                                                                                    Process: com.armutyus.cameraxproject, PID: 25488
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material/TouchTargetKt;
                                                                                                    	at com.smarttoolfactory.slider.MinimumTouchKt$minimumTouchTargetSize$2.invoke(MinimumTouch.kt:27)
                                                                                                    	at com.smarttoolfactory.slider.MinimumTouchKt$minimumTouchTargetSize$2.invoke(MinimumTouch.kt:19)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:265)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:260)
                                                                                                    	at androidx.compose.ui.Modifier$Element.foldIn(Modifier.kt:115)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:301)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:260)
                                                                                                    	at androidx.compose.ui.layout.SubcomposeLayoutKt.SubcomposeLayout(SubcomposeLayout.kt:110)
                                                                                                    	at androidx.compose.ui.layout.SubcomposeLayoutKt.SubcomposeLayout(SubcomposeLayout.kt:75)
                                                                                                    	at androidx.compose.foundation.layout.BoxWithConstraintsKt.BoxWithConstraints(BoxWithConstraints.kt:67)
                                                                                                    	at com.smarttoolfactory.slider.ColorfulSliderKt.ColorfulSlider-rpZKZhI(ColorfulSlider.kt:168)
                                                                                                    	at com.smarttoolfactory.slider.ColorfulSliderKt.ColorfulSlider-rpZKZhI(ColorfulSlider.kt:86)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.SelectionWidgetsKt.SliderSelection(SelectionWidgets.kt:103)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.CropPropertySelectionKt.CropPropertySelectionMenu(CropPropertySelection.kt:79)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.PropertySelectionSheetKt$PropertySelectionSheet$1.invoke(PropertySelectionSheet.kt:14)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.PropertySelectionSheetKt$PropertySelectionSheet$1.invoke(PropertySelectionSheet.kt:13)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.BaseSheetKt$BaseSheet$1.invoke(BaseSheet.kt:43)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.BaseSheetKt$BaseSheet$1.invoke(BaseSheet.kt:17)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.BaseSheetKt.BaseSheet(BaseSheet.kt:17)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.cropproperties.PropertySelectionSheetKt.PropertySelectionSheet(PropertySelectionSheet.kt:13)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.ImageCropModeKt$ImageCropMode$5.invoke(ImageCropMode.kt:144)
                                                                                                    	at com.armutyus.cameraxproject.ui.gallery.preview.editmedia.ImageCropModeKt$ImageCropMode$5.invoke(ImageCropMode.kt:142)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1$6.invoke(ModalBottomSheet.kt:718)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1$6.invoke(ModalBottomSheet.kt:541)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
2023-03-24 14:45:34.907 25488-25488 AndroidRuntime          com.armutyus.cameraxproject          E  	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:137)
                                                                                                    	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:115)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:468)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:454)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1$measurables$1.invoke(BoxWithConstraints.kt:69)
                                                                                                    	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1$measurables$1.invoke(BoxWithConstraints.kt:69)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:778)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:446)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3352)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3342)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3342)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3277)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:966)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3952)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3952)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3952)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:466)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:439)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:430)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:419)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:740)
                                                                                                    	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke-0kLqBqw(BoxWithConstraints.kt:69)
                                                                                                    	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke(BoxWithConstraints.kt:67)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:598)
2023-03-24 14:45:34.908 25488-25488 AndroidRuntime          com.armutyus.cameraxproject          E  	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:103)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1090)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1086)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:107)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1086)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:342)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:321)
                                                                                                    	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:115)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:103)
                                                                                                    	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:635)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1090)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1086)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:107)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1086)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:342)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1173)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1164)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:309)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:434)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:39)
2023-03-24 14:45:34.915 25488-25488 AndroidRuntime          com.armutyus.cameraxproject          E  	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:330)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:778)
                                                                                                    	at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:216)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1008)
                                                                                                    	at android.view.View.draw(View.java:22508)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21367)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21325)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21325)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21325)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21325)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:567)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:651)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4274)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3979)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3240)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2066)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8496)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:826)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8061)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.material.TouchTargetKt" on path: DexPathList[[zip file "/data/app/~~nYn-U1LtzSuDMkLL47qYfQ==/com.armutyus.cameraxproject-sdiOo9qvherHnO-50oo1yw==/base.apk"],nativeLibraryDirectories=[/data/app/~~nYn-U1LtzSuDMkLL47qYfQ==/com.armutyus.cameraxproject-sdiOo9qvherHnO-50oo1yw==/lib/arm64, /data/app/~~nYn-U1LtzSuDMkLL47qYfQ==/com.armutyus.cameraxproject-sdiOo9qvherHnO-50oo1yw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 151 more`

**Comment by armutyus** [comment]
> check and delete if you have implemented`androidx.compose.material3` library

Thanks for your suggestion but i am using material3 library. Also i solved it and edited my post to reference old issue.

**Comment by SmartToolFactory** [comment]
Would you mind testing with newest release? Updated dependencies.

**Comment by armutyus** [comment]
I'll check it and tell you the results.

**Comment by SmartToolFactory** [comment]
This issue should be fixed in 0.4.0
